name= input("enter your name:").lower()
print(name.lower())

print(name.upper())
print(name.title())
print(name.capitalize())
print(name.swapcase())
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.replace("komal","ruhi"))
print(name.split())
print(name.find("p"))
print(name.count("k"))
print(name. center(100))
print (name. ljust(100))
print(name.rjust(100))